apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: celery
  name: celery-controller
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: taskQueue
        component: celery
    spec:
      containers:
      - image: mven/celery-worker:3.0
        imagePullPolicy: IfNotPresent
        name: celery
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
        nodeSelector:
          app_type: worker
